export const STRUCTURE_TURRETS = {

  "A0BaBaBunker": ['gnmmg1.pie', 'trmmg.pie'],
  "A0BaBaFlameTower": ['gnlflmr.pie', 'trlflmr.pie'],
  "A0BaBaGunTower": [],
  "A0BaBaGunTowerEND": [],
  "A0BaBaMortarPit": ['gnmmort.pie', 'trmmort.pie'],
  "A0BaBaRocketPit": ['gnlrcktp.pie', 'trlrcktp.pie'],
  "A0BaBaRocketPitAT": ['gnlmsl.pie', 'trlrckt.pie'],
  "A0CannonTower": [],
  "A0LasSatCommand": ['gnlassat.pie', 'trlassat.pie'],
  "AASite-QuadBof": ['gnmair2.pie', 'trmair2.pie'],
  "AASite-QuadMg1": ['gnlair.pie', 'trmair.pie'],
  "AASite-QuadRotMg": ['gnhair2.pie', 'trhair.pie'],
  "CO-Tower-HVCan": ['gnlacan.pie', 'trlacan.pie'],
  "CO-Tower-HvATRkt": ['gnmrcktb.pie', 'trmrcktb.pie'],
  "CO-Tower-HvFlame": ['gnmflmr.pie', 'trmflmr.pie'],
  "CO-Tower-LtATRkt": ['gnmrckta.pie', 'trmrckta.pie'],
  "CO-Tower-MG3": ['gnmmg1.pie', 'trmmg.pie'],
  "CO-Tower-MdCan": ['gnmcan.pie', 'trmcan.pie'],
  "CO-Tower-RotMG": ['gnmmg2.pie', 'trmmg.pie'],
  "CO-WallTower-HvCan": ['gnhcan.pie', 'trhcan.pie'],
  "CO-WallTower-RotCan": ['gnmvcan.pie', 'trmvcan.pie'],
  "Emplacement-HPVcannon": ['gnlacan.pie', 'trlacan.pie'],
  "Emplacement-HeavyLaser": ['gnhlas.pie', 'trhlas.pie'],
  "Emplacement-Howitzer-Incenediary": ['gnmhowti.pie', 'trmhowt.pie'],
  "Emplacement-Howitzer105": ['gnmhowt.pie', 'trmhowt.pie'],
  "Emplacement-Howitzer150": ['gnhhowt.pie', 'trhhowt.pie'],
  "Emplacement-HvART-pit": ['gnhmslab.pie', 'trhmslab.pie'],
  "Emplacement-HvyATrocket": ['gnmrcktb.pie', 'trmrcktb.pie'],
  "Emplacement-MRL-pit": ['gnmrckt.pie', 'trmrckt.pie'],
  "Emplacement-MdART-pit": ['gnmmslaa.pie', 'trmmslaa.pie'],
  "Emplacement-MortarEMP": ['gnhmorte.pie', 'trhrmort.pie'],
  "Emplacement-MortarPit-Incenediary": ['gnmmorti.pie', 'trmmort.pie'],
  "Emplacement-MortarPit01": ['gnmmort.pie', 'trmmort.pie'],
  "Emplacement-MortarPit02": ['gnhmort2.pie', 'trhrmort.pie'],
  "Emplacement-PlasmaCannon": ['gnhplsma.pie', 'trhlas.pie'],
  "Emplacement-PrisLas": ['gnmrlas.pie', 'trmlas.pie'],
  "Emplacement-PulseLaser": ['gnmlas.pie', 'trmlas.pie'],
  "Emplacement-Rail2": ['gnmgss.pie', 'trmgss.pie'],
  "Emplacement-Rail3": ['gnhgss.pie', 'trhgss.pie'],
  "Emplacement-Rocket06-IDF": ['gnhrckt.pie', 'trhrckt.pie'],
  "Emplacement-RotHow": ['gnhhowt2.pie', 'trhhow2.pie'],
  "Emplacement-RotMor": ['gnhmort.pie', 'trhrmort.pie'],
  "GuardTower-ATMiss": ['gnmmslat.pie', 'trmmslat.pie'],
  "GuardTower-BeamLas": ['gnmlas.pie', 'trmlas.pie'],
  "GuardTower-Rail1": ['gnlgss.pie', 'trlgss.pie'],
  "GuardTower-RotMg": ['gnmmg2.pie', 'trmmg.pie'],
  "GuardTower1": ['gnmmg1.pie', 'trmmg.pie'],
  "GuardTower2": ['gnlmg2.pie', 'trlmg2.pie'],
  "GuardTower3": ['gnmmg1.pie', 'trmmg.pie'],
  "GuardTower4": ['gnlflmr.pie', 'trlflmr.pie'],
  "GuardTower5": ['gnmrckta.pie', 'trmrckta.pie'],
  "GuardTower6": ['gnlrcktp.pie', 'trlrcktp.pie'],
  "NX-Emp-MedArtMiss-Pit": ['gnmmslaa.pie', 'trmmslaa.pie'],
  "NX-Emp-MultiArtMiss-Pit": ['gnhmslab.pie', 'trhmslab.pie'],
  "NX-Emp-Plasma-Pit": ['gnhplasm.pie', 'trhplasm.pie'],
  "NX-Tower-ATMiss": ['gnmmslat.pie', 'trmmslat.pie'],
  "NX-Tower-PulseLas": ['gnmlas.pie', 'trmlas.pie'],
  "NX-Tower-Rail1": ['gnlgss.pie', 'trlgss.pie'],
  "NX-WallTower-BeamLas": ['gnmrlas.pie', 'trmlas.pie'],
  "NX-WallTower-Rail2": ['gnmgss.pie', 'trmgss.pie'],
  "NX-WallTower-Rail3": ['gnhgss.pie', 'trhgss.pie'],
  "P0-AASite-Laser": ['gnhaalas.pie', 'trhmslsa.pie'],
  "P0-AASite-SAM1": ['gnmmslsa.pie', 'trmmslsa.pie'],
  "P0-AASite-SAM2": ['gnhmslsa.pie', 'trhmslsa.pie'],
  "P0-AASite-Sunburst": ['gnmair3.pie', 'trmair3.pie'],
  "PillBox-Cannon6": ['gnhvcan2.pie', 'trhvcan2.pie'],
  "PillBox1": [],
  "PillBox2": [],
  "PillBox3": [],
  "PillBox4": ['gnlcan.pie', 'trlcan.pie'],
  "PillBox5": ['gnlflmr.pie', 'trlflmr.pie'],
  "PillBox6": ['gnmrckta.pie', 'trmrckta.pie'],
  "Pillbox-RotMG": [],
  "Plasmite-flamer-bunker": ['gnmflmrp.pie', 'trmflmrp.pie'],
  "Sys-NEXUSLinkTOW": ['gnhecm3.pie', 'trhecm3.pie'],
  "Sys-SpyTower": ['gnhecm3.pie', 'trhecm3.pie'],
  "Tower-Projector": ['gnmflmr.pie', 'trmflmr.pie'],
  "Tower-RotMg": ['gnmmg2.pie', 'trmmg.pie'],
  "Tower-VulcanCan": ['gnlacan.pie', 'trlacan.pie'],
  "Wall-RotMg": ['gnmmg2.pie', 'trmmg.pie'],
  "Wall-VulcanCan": ['gnmvcan.pie', 'trmvcan.pie'],
  "WallTower-Atmiss": ['gnmmslat.pie', 'trmmslat.pie'],
  "WallTower-DoubleAAGun": ['gnmair2.pie', 'trmair2.pie'],
  "WallTower-EMP": ['gnhemp.pie', 'trhemp.pie'],
  "WallTower-HPVcannon": ['gnlacan.pie', 'trlacan.pie'],
  "WallTower-HvATrocket": ['gnmrcktb.pie', 'trmrcktb.pie'],
  "WallTower-Projector": ['gnmflmr.pie', 'trmflmr.pie'],
  "WallTower-PulseLas": ['gnmlas.pie', 'trmlas.pie'],
  "WallTower-QuadRotAAGun": ['gnhair2.pie', 'trhair.pie'],
  "WallTower-Rail2": ['gnmgss.pie', 'trmgss.pie'],
  "WallTower-Rail3": ['gnhgss.pie', 'trhgss.pie'],
  "WallTower-SamHvy": ['gnhmslsa.pie', 'trhmslsa.pie'],
  "WallTower-SamSite": ['gnmmslsa.pie', 'trmmslsa.pie'],
  "WallTower-TwinAssaultGun": ['gnhmg1.pie', 'trhmg.pie'],
  "WallTower01": ['gnmmg1.pie', 'trmmg.pie'],
  "WallTower02": ['gnlcan.pie', 'trlcan.pie'],
  "WallTower03": ['gnmcan.pie', 'trmcan.pie'],
  "WallTower04": ['gnhcan.pie', 'trhcan.pie'],
  "WallTower05": ['gnlflmr.pie', 'trlflmr.pie'],
  "WallTower06": ['gnmrckta.pie', 'trmrckta.pie'],
  "X-Super-Cannon": ['gnwpfcan.pie', 'trwpfcan.pie'],
  "X-Super-MassDriver": ['gnwpfgss.pie', 'trwpfgss.pie'],
  "X-Super-Missile": ['gnwpfmsl.pie', 'trwpfmsl.pie'],
  "X-Super-Rocket": ['gnwpfrkt.pie', 'trwpfrkt.pie']
};
